# Generated by Django 6.1 on 2026-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('species', models.CharField(max_length=50, verbose_name='Especie')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Nombre del Dueño')),
                ('reason', models.TextField(verbose_name='Motivo de Consulta')),
                ('date', models.DateField(verbose_name='Fecha de Atención')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
    ]
